programa: compr.o main.o
	gcc -Wall -Wextra -Werror -ansi -pedantic -o programa compr.o main.o

compr.o: compr.c
	gcc -Wall -Wextra -Werror -ansi -pedantic -o compr.o -c compr.c

main.o: main.c
	gcc -Wall -Wextra -Werror -ansi -pedantic -o main.o -c main.c