programa: comp.o test.o
	gcc -Wall -Wextra -Werror -ansi -pedantic -o programa comp.o test.o

compr.o: compr.c
	gcc -Wall -Wextra -Werror -ansi -pedantic -o compr.o -c compr.c

main.o: main.c
	gcc -Wall -Wextra -Werror -ansi -pedantic -o main.o -c main.c
test.o: test.c
	gcc -Wall -Wextra -Werror -ansi -pedantic -o test.o -c test.c