programa: ejercicioGrep.o
	gcc -Wall -Wextra -Werror -ansi -pedantic -o programa ejercicioGrep.o

ejercicioGrep.o: ejercicioGrep.c
	gcc -Wall -Wextra -Werror -ansi -pedantic -o ejercicioGrep.o -c ejercicioGrep.c