programa: comp.o main.o
	gcc -Wall -Wextra -Werror -ansi -pedantic -o programa comp.o main.o

comp.o: comp.c
	gcc -Wall -Wextra -Werror -ansi -pedantic -o comp.o -c comp.c

main.o: main.c
	gcc -Wall -Wextra -Werror -ansi -pedantic -o main.o -c main.c