programa: comp.o test.o
	gcc -Wall -Wextra -Werror -ansi -pedantic -o programa comp.o test.o

comp.o: comp.c
	gcc -Wall -Wextra -Werror -ansi -pedantic -o comp.o -c comp.c

main.o: main.c
	gcc -Wall -Wextra -Werror -ansi -pedantic -o main.o -c main.c
test.o: test.c
	gcc -Wall -Wextra -Werror -ansi -pedantic -o test.o -c test.c